on:
  push:
    branches: [main, master, rc-**]
  pull_request:
    branches: [main, master]
  schedule:
    - cron:  '0 11 * * 1' # every monday

name: Package checks

jobs:
  website:
    uses: rstudio/shinycoreci/.github/workflows/call-website.yaml@v1
  routine:
    uses: rstudio/shinycoreci/.github/workflows/call-routine.yaml@v1
  R-CMD-check:
    uses: rstudio/shinycoreci/.github/workflows/call-R-CMD-check.yaml@v1
